const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');

class InMemoryDB {
  constructor() {
    this.initialized = false;
    this.users = [];
    this.students = [];
    this.courses = [];
    this.applications = [];
    this.documents = [];
    this.payments = [];
    this.notifications = [];
    this.auditLogs = [];
    this.admissionCycles = [];
    this.initDefaultData();
  }

  initDefaultData() {
    const defaultPasswordHash = bcrypt.hashSync('Admin@123', 10);
    const officerPasswordHash = bcrypt.hashSync('Officer@123', 10);
    const studentPasswordHash = bcrypt.hashSync('Student@123', 10);

    // 1. Admission Cycle
    this.admissionCycles = [
      {
        _id: 'cycle-2026-1',
        cycleCode: 'IEM-ADM-2026',
        title: 'Academic Session 2026 - 2027 UG & PG Admissions',
        academicYear: '2026-2027',
        startDate: new Date('2026-01-01'),
        endDate: new Date('2026-11-30'),
        applicationFee: 2000,
        isActive: true,
        announcement: 'Admissions Open for B.Tech, BCA, MCA, BBA, and MBA programs for Batch 2026-2030.',
        createdAt: new Date(),
      },
    ];

    // 2. Users
    this.users = [
      {
        _id: 'usr-admin-1',
        name: 'Prof. Debashis De',
        email: 'admin@iem.edu.in',
        password: defaultPasswordHash,
        role: 'admin',
        phone: '+91 9830012345',
        department: 'School of Engineering & Technology',
        isActive: true,
        isEmailVerified: true,
        createdAt: new Date('2026-01-01'),
      },
      {
        _id: 'usr-off-1',
        name: 'Dr. Arindam Mukherjee',
        email: 'officer.engg@iem.edu.in',
        password: officerPasswordHash,
        role: 'officer',
        phone: '+91 9831122334',
        department: 'School of Engineering & Technology',
        isActive: true,
        isEmailVerified: true,
        createdAt: new Date('2026-01-05'),
      },
      {
        _id: 'usr-off-2',
        name: 'Dr. Sarmistha Ghosh',
        email: 'officer.mgmt@iem.edu.in',
        password: officerPasswordHash,
        role: 'officer',
        phone: '+91 9832233445',
        department: 'School of Management',
        isActive: true,
        isEmailVerified: true,
        createdAt: new Date('2026-01-05'),
      },
      {
        _id: 'usr-std-1',
        name: 'Rahul Roy',
        email: 'student.rahul@gmail.com',
        password: studentPasswordHash,
        role: 'student',
        phone: '+91 9876543210',
        isActive: true,
        isEmailVerified: true,
        createdAt: new Date('2026-02-01'),
      },
      {
        _id: 'usr-std-2',
        name: 'Priya Sen',
        email: 'student.priya@gmail.com',
        password: studentPasswordHash,
        role: 'student',
        phone: '+91 9876543211',
        isActive: true,
        isEmailVerified: true,
        createdAt: new Date('2026-02-05'),
      },
      {
        _id: 'usr-std-3',
        name: 'Sneha Chakraborty',
        email: 'student.sneha@gmail.com',
        password: studentPasswordHash,
        role: 'student',
        phone: '+91 9876543212',
        isActive: true,
        isEmailVerified: true,
        createdAt: new Date('2026-02-10'),
      },
    ];

    // 3. Courses
    this.courses = [
      {
        _id: 'crs-btech-cse',
        courseCode: 'BTECH-CSE',
        name: 'B.Tech in Computer Science & Engineering',
        department: 'Department of Computer Science & Engineering',
        level: 'UG',
        duration: '4 Years (8 Semesters)',
        eligibilityCriteria: 'Minimum 60% in Class 12 with PCM. Valid WBJEE / JEE Main / IEMJEE rank.',
        minimumPCMPercentage: 60,
        acceptedExams: ['WBJEE', 'JEE Main', 'IEMJEE'],
        totalSeats: 240,
        availableSeats: 180,
        feesStructure: {
          admissionFee: 30000,
          perSemesterTuition: 87500,
          totalSemesters: 8,
          cautionDeposit: 10000,
          libraryAndLabFee: 15000,
          totalCourseFee: 755000,
        },
        isActive: true,
      },
      {
        _id: 'crs-btech-it',
        courseCode: 'BTECH-IT',
        name: 'B.Tech in Information Technology',
        department: 'Department of Information Technology',
        level: 'UG',
        duration: '4 Years (8 Semesters)',
        eligibilityCriteria: 'Minimum 60% in Class 12 PCM. Valid WBJEE / JEE Main rank.',
        minimumPCMPercentage: 60,
        acceptedExams: ['WBJEE', 'JEE Main', 'IEMJEE'],
        totalSeats: 120,
        availableSeats: 95,
        feesStructure: {
          admissionFee: 30000,
          perSemesterTuition: 85000,
          totalSemesters: 8,
          cautionDeposit: 10000,
          libraryAndLabFee: 15000,
          totalCourseFee: 735000,
        },
        isActive: true,
      },
      {
        _id: 'crs-btech-ece',
        courseCode: 'BTECH-ECE',
        name: 'B.Tech in Electronics & Communication Engineering',
        department: 'Department of Electronics & Communication',
        level: 'UG',
        duration: '4 Years (8 Semesters)',
        eligibilityCriteria: 'Minimum 55% in Class 12 PCM. Valid WBJEE / JEE Main rank.',
        minimumPCMPercentage: 55,
        acceptedExams: ['WBJEE', 'JEE Main', 'IEMJEE'],
        totalSeats: 180,
        availableSeats: 140,
        feesStructure: {
          admissionFee: 30000,
          perSemesterTuition: 82500,
          totalSemesters: 8,
          cautionDeposit: 10000,
          libraryAndLabFee: 15000,
          totalCourseFee: 715000,
        },
        isActive: true,
      },
      {
        _id: 'crs-bca',
        courseCode: 'BCA',
        name: 'Bachelor of Computer Applications (BCA)',
        department: 'Department of Computer Applications',
        level: 'UG',
        duration: '3 Years (6 Semesters)',
        eligibilityCriteria: 'Passed 10+2 with Mathematics / CS with 50% marks.',
        minimumPCMPercentage: 50,
        acceptedExams: ['IEMJEE', 'Direct / Merit'],
        totalSeats: 120,
        availableSeats: 70,
        feesStructure: {
          admissionFee: 20000,
          perSemesterTuition: 45000,
          totalSemesters: 6,
          cautionDeposit: 8000,
          libraryAndLabFee: 10000,
          totalCourseFee: 308000,
        },
        isActive: true,
      },
      {
        _id: 'crs-mca',
        courseCode: 'MCA',
        name: 'Master of Computer Applications (MCA)',
        department: 'Department of Computer Applications',
        level: 'PG',
        duration: '2 Years (4 Semesters)',
        eligibilityCriteria: 'Graduation in BCA / B.Sc (IT/CS) with minimum 50% marks. Valid WB-JECA rank.',
        minimumPCMPercentage: 50,
        acceptedExams: ['Direct / Merit', 'Other'],
        totalSeats: 60,
        availableSeats: 42,
        feesStructure: {
          admissionFee: 25000,
          perSemesterTuition: 65000,
          totalSemesters: 4,
          cautionDeposit: 10000,
          libraryAndLabFee: 12000,
          totalCourseFee: 307000,
        },
        isActive: true,
      },
      {
        _id: 'crs-bba',
        courseCode: 'BBA',
        name: 'Bachelor of Business Administration (BBA)',
        department: 'School of Management',
        level: 'UG',
        duration: '3 Years (6 Semesters)',
        eligibilityCriteria: 'Passed 10+2 with English with 50% aggregate marks.',
        minimumPCMPercentage: 45,
        acceptedExams: ['IEMJEE', 'Direct / Merit'],
        totalSeats: 120,
        availableSeats: 88,
        feesStructure: {
          admissionFee: 20000,
          perSemesterTuition: 50000,
          totalSemesters: 6,
          cautionDeposit: 8000,
          libraryAndLabFee: 8000,
          totalCourseFee: 336000,
        },
        isActive: true,
      },
      {
        _id: 'crs-mba',
        courseCode: 'MBA',
        name: 'Master of Business Administration (MBA)',
        department: 'School of Management',
        level: 'PG',
        duration: '2 Years (4 Semesters)',
        eligibilityCriteria: 'Graduation with 50% marks. Valid CAT/MAT/JEMAT/IEMJEE score.',
        minimumPCMPercentage: 50,
        acceptedExams: ['CAT', 'MAT', 'IEMJEE'],
        totalSeats: 120,
        availableSeats: 65,
        feesStructure: {
          admissionFee: 35000,
          perSemesterTuition: 95000,
          totalSemesters: 4,
          cautionDeposit: 10000,
          libraryAndLabFee: 15000,
          totalCourseFee: 440000,
        },
        isActive: true,
      },
    ];

    // 4. Student Profiles
    this.students = [
      {
        _id: 'std-p-1',
        user: 'usr-std-1',
        studentId: 'IEM-STD-2026-4912',
        dob: new Date('2005-04-12'),
        gender: 'Male',
        bloodGroup: 'B+',
        nationality: 'Indian',
        category: 'General',
        isPhysicallyChallenged: false,
        guardian: {
          fatherName: 'Swapan Roy',
          fatherOccupation: 'Government Service',
          fatherPhone: '+91 9830099887',
          motherName: 'Anjana Roy',
          motherOccupation: 'Teacher',
          motherPhone: '+91 9830099888',
          annualIncome: 850000,
        },
        address: {
          present: {
            street: 'Block BD, Plot 14, Salt Lake Sector 1',
            city: 'Kolkata',
            district: 'North 24 Parganas',
            state: 'West Bengal',
            pincode: '700064',
            country: 'India',
          },
          permanent: {
            street: 'Block BD, Plot 14, Salt Lake Sector 1',
            city: 'Kolkata',
            district: 'North 24 Parganas',
            state: 'West Bengal',
            pincode: '700064',
            country: 'India',
            sameAsPresent: true,
          },
        },
        academics: {
          class10: {
            board: 'WBBSE',
            schoolName: 'Salt Lake School',
            passingYear: 2021,
            rollNumber: 'WBBSE-102934',
            totalMarks: 700,
            marksObtained: 616,
            percentage: 88,
          },
          class12: {
            board: 'WBCHSE',
            schoolName: 'Salt Lake School',
            passingYear: 2023,
            stream: 'Science',
            rollNumber: 'WBCHSE-492019',
            totalMarks: 500,
            marksObtained: 445,
            percentage: 89,
            pcmPercentage: 91,
          },
          entranceExam: {
            examType: 'WBJEE',
            rollNumber: 'WBJEE-2026-49281',
            rank: 2150,
            score: 84.5,
            examYear: 2026,
          },
        },
        profileCompleted: true,
        completionPercentage: 100,
      },
      {
        _id: 'std-p-2',
        user: 'usr-std-2',
        studentId: 'IEM-STD-2026-8821',
        dob: new Date('2005-08-25'),
        gender: 'Female',
        bloodGroup: 'O+',
        nationality: 'Indian',
        category: 'General',
        guardian: {
          fatherName: 'Debjit Sen',
          fatherOccupation: 'Business',
          fatherPhone: '+91 9433112233',
          motherName: 'Madhumita Sen',
          annualIncome: 1200000,
        },
        address: {
          present: {
            street: '45/B Southern Avenue',
            city: 'Kolkata',
            state: 'West Bengal',
            pincode: '700029',
          },
        },
        academics: {
          class10: { board: 'CBSE', passingYear: 2021, percentage: 92 },
          class12: { board: 'CBSE', passingYear: 2023, percentage: 91, pcmPercentage: 93 },
          entranceExam: { examType: 'JEE Main', rank: 18450, score: 94.2 },
        },
        profileCompleted: true,
        completionPercentage: 100,
      },
      {
        _id: 'std-p-3',
        user: 'usr-std-3',
        studentId: 'IEM-STD-2026-9034',
        dob: new Date('2004-11-19'),
        gender: 'Female',
        bloodGroup: 'A+',
        category: 'OBC-A',
        guardian: { fatherName: 'Subhasish Chakraborty', annualIncome: 600000 },
        address: { present: { city: 'Kolkata', state: 'West Bengal', pincode: '700156' } },
        academics: {
          class10: { board: 'ICSE', percentage: 86 },
          class12: { board: 'ISC', percentage: 88 },
          entranceExam: { examType: 'IEMJEE', rank: 320, score: 78 },
        },
        profileCompleted: true,
        completionPercentage: 85,
      },
    ];

    // 5. Applications
    this.applications = [
      {
        _id: 'app-iem-1',
        applicationNumber: 'IEM-2026-881023',
        user: 'usr-std-1',
        student: 'std-p-1',
        course: 'crs-btech-cse',
        admissionCycle: '2026-2027',
        status: 'APPROVED',
        currentStep: 6,
        isFeePaid: true,
        submissionDate: new Date('2026-02-10T10:00:00Z'),
        assignedOfficer: 'usr-off-1',
        officerRemarks: 'Academic records verified and PCM marks exceed cutoff. Approved for B.Tech CSE seat allocation.',
        decisionDate: new Date('2026-02-15T14:20:00Z'),
        admissionOfferLetterGenerated: true,
        meritScore: 91.5,
        timeline: [
          { status: 'SUBMITTED', actorName: 'Rahul Roy', role: 'student', comment: 'Application submitted with mock fee payment.', timestamp: new Date('2026-02-10T10:00:00Z') },
          { status: 'UNDER_REVIEW', actorName: 'Dr. Arindam Mukherjee', role: 'officer', comment: 'Application taken up for document screening.', timestamp: new Date('2026-02-12T11:30:00Z') },
          { status: 'APPROVED', actorName: 'Dr. Arindam Mukherjee', role: 'officer', comment: 'All qualifications verified. Admission granted.', timestamp: new Date('2026-02-15T14:20:00Z') },
        ],
        createdAt: new Date('2026-02-10T10:00:00Z'),
      },
      {
        _id: 'app-iem-2',
        applicationNumber: 'IEM-2026-912044',
        user: 'usr-std-2',
        student: 'std-p-2',
        course: 'crs-btech-it',
        admissionCycle: '2026-2027',
        status: 'UNDER_REVIEW',
        currentStep: 6,
        isFeePaid: true,
        submissionDate: new Date('2026-02-18T12:00:00Z'),
        assignedOfficer: 'usr-off-1',
        officerRemarks: 'Class 12 verification ongoing. Roll number confirmed with board portal.',
        meritScore: 92.0,
        timeline: [
          { status: 'SUBMITTED', actorName: 'Priya Sen', role: 'student', comment: 'Application submitted.', timestamp: new Date('2026-02-18T12:00:00Z') },
          { status: 'UNDER_REVIEW', actorName: 'Dr. Arindam Mukherjee', role: 'officer', comment: 'Assigned to engineering review desk.', timestamp: new Date('2026-02-19T09:00:00Z') },
        ],
        createdAt: new Date('2026-02-18T12:00:00Z'),
      },
      {
        _id: 'app-iem-3',
        applicationNumber: 'IEM-2026-304192',
        user: 'usr-std-3',
        student: 'std-p-3',
        course: 'crs-bba',
        admissionCycle: '2026-2027',
        status: 'SUBMITTED',
        currentStep: 6,
        isFeePaid: true,
        submissionDate: new Date('2026-02-22T15:45:00Z'),
        assignedOfficer: 'usr-off-2',
        meritScore: 88.0,
        timeline: [
          { status: 'SUBMITTED', actorName: 'Sneha Chakraborty', role: 'student', comment: 'Application submitted for BBA program.', timestamp: new Date('2026-02-22T15:45:00Z') },
        ],
        createdAt: new Date('2026-02-22T15:45:00Z'),
      },
    ];

    // 6. Documents
    this.documents = [
      {
        _id: 'doc-1',
        user: 'usr-std-1',
        student: 'std-p-1',
        application: 'app-iem-1',
        documentType: 'CLASS_10_MARKSHEET',
        title: 'Class 10 Board Marksheet',
        originalFileName: 'rahul_class_10_marksheet.pdf',
        fileName: 'doc_class10_102934.pdf',
        filePath: '/uploads/documents/doc_class10_102934.pdf',
        fileUrl: '/uploads/documents/doc_class10_102934.pdf',
        fileSize: 420000,
        mimeType: 'application/pdf',
        status: 'VERIFIED',
        verificationRemarks: 'WBBSE Marks verified with official board results.',
        verifiedBy: 'usr-off-1',
        verifiedAt: new Date('2026-02-14'),
        createdAt: new Date('2026-02-10'),
      },
      {
        _id: 'doc-2',
        user: 'usr-std-1',
        student: 'std-p-1',
        application: 'app-iem-1',
        documentType: 'CLASS_12_MARKSHEET',
        title: 'Class 12 Higher Secondary Marksheet',
        originalFileName: 'rahul_wbchse_12.pdf',
        fileName: 'doc_class12_492019.pdf',
        filePath: '/uploads/documents/doc_class12_492019.pdf',
        fileUrl: '/uploads/documents/doc_class12_492019.pdf',
        fileSize: 480000,
        mimeType: 'application/pdf',
        status: 'VERIFIED',
        verificationRemarks: 'PCM score 91% verified.',
        verifiedBy: 'usr-off-1',
        verifiedAt: new Date('2026-02-14'),
        createdAt: new Date('2026-02-10'),
      },
      {
        _id: 'doc-3',
        user: 'usr-std-1',
        student: 'std-p-1',
        application: 'app-iem-1',
        documentType: 'ENTRANCE_SCORECARD',
        title: 'WBJEE 2026 Rank Card',
        originalFileName: 'wbjee_rank_card.pdf',
        fileName: 'doc_wbjee_rank.pdf',
        filePath: '/uploads/documents/doc_wbjee_rank.pdf',
        fileUrl: '/uploads/documents/doc_wbjee_rank.pdf',
        fileSize: 310000,
        mimeType: 'application/pdf',
        status: 'VERIFIED',
        verificationRemarks: 'WBJEE Rank 2150 confirmed.',
        verifiedBy: 'usr-off-1',
        verifiedAt: new Date('2026-02-14'),
        createdAt: new Date('2026-02-10'),
      },
      {
        _id: 'doc-4',
        user: 'usr-std-2',
        student: 'std-p-2',
        application: 'app-iem-2',
        documentType: 'CLASS_12_MARKSHEET',
        title: 'CBSE 12th Marksheet',
        originalFileName: 'priya_cbse12.pdf',
        fileName: 'doc_priya_cbse12.pdf',
        filePath: '/uploads/documents/doc_priya_cbse12.pdf',
        fileUrl: '/uploads/documents/doc_priya_cbse12.pdf',
        fileSize: 410000,
        mimeType: 'application/pdf',
        status: 'PENDING',
        verificationRemarks: 'Awaiting board verification API handshake.',
        createdAt: new Date('2026-02-18'),
      },
    ];

    // 7. Payments
    this.payments = [
      {
        _id: 'pay-1',
        transactionId: 'TXN-IEM-20260210-9102',
        orderId: 'ORD-IEM-1707560000',
        receiptNumber: 'RCP-IEM-491023',
        user: 'usr-std-1',
        student: 'std-p-1',
        application: 'app-iem-1',
        amount: 2000,
        currency: 'INR',
        paymentType: 'APPLICATION_FEE',
        paymentMethod: 'UPI',
        status: 'SUCCESS',
        paymentGatewayResponse: { gateway: 'IEM Mock Gateway', status: 'SUCCESS', referenceId: 'REF_991823' },
        paidAt: new Date('2026-02-10T10:05:00Z'),
        createdAt: new Date('2026-02-10T10:05:00Z'),
      },
      {
        _id: 'pay-2',
        transactionId: 'TXN-IEM-20260218-4412',
        orderId: 'ORD-IEM-1708250000',
        receiptNumber: 'RCP-IEM-912044',
        user: 'usr-std-2',
        student: 'std-p-2',
        application: 'app-iem-2',
        amount: 2000,
        currency: 'INR',
        paymentType: 'APPLICATION_FEE',
        paymentMethod: 'CREDIT_CARD',
        status: 'SUCCESS',
        paymentGatewayResponse: { gateway: 'IEM Mock Gateway', status: 'SUCCESS' },
        paidAt: new Date('2026-02-18T12:05:00Z'),
        createdAt: new Date('2026-02-18T12:05:00Z'),
      },
      {
        _id: 'pay-3',
        transactionId: 'TXN-IEM-20260222-1184',
        orderId: 'ORD-IEM-1708600000',
        receiptNumber: 'RCP-IEM-304192',
        user: 'usr-std-3',
        student: 'std-p-3',
        application: 'app-iem-3',
        amount: 2000,
        currency: 'INR',
        paymentType: 'APPLICATION_FEE',
        paymentMethod: 'UPI',
        status: 'SUCCESS',
        paidAt: new Date('2026-02-22T15:50:00Z'),
        createdAt: new Date('2026-02-22T15:50:00Z'),
      },
    ];

    // 8. Notifications
    this.notifications = [
      {
        _id: 'notif-1',
        recipient: 'usr-std-1',
        targetRole: 'student',
        title: 'Congratulations! Admission Application Approved',
        message: 'Your application IEM-2026-881023 for B.Tech in CSE has been approved. You can download your official Admission Slip.',
        type: 'SUCCESS',
        isRead: false,
        createdAt: new Date('2026-02-15T14:20:00Z'),
      },
      {
        _id: 'notif-2',
        recipient: 'usr-std-2',
        targetRole: 'student',
        title: 'Application Under Review',
        message: 'Your application IEM-2026-912044 is currently under verification by the admission committee.',
        type: 'INFO',
        isRead: true,
        createdAt: new Date('2026-02-19T09:00:00Z'),
      },
      {
        _id: 'notif-3',
        recipient: null,
        targetRole: 'all',
        title: 'IEM Kolkata Admission Notice 2026',
        message: 'Last date for submission of Class 12 improvement marksheets is 15th October 2026.',
        type: 'ANNOUNCEMENT',
        isRead: false,
        createdAt: new Date('2026-02-01T08:00:00Z'),
      },
    ];

    // 9. Audit Logs
    this.auditLogs = [
      {
        _id: 'aud-1',
        user: 'usr-off-1',
        userEmail: 'officer.engg@iem.edu.in',
        role: 'officer',
        action: 'APPLICATION_STATUS_APPROVED',
        module: 'APPLICATION',
        details: { applicationNumber: 'IEM-2026-881023', course: 'BTECH-CSE' },
        createdAt: new Date('2026-02-15T14:20:00Z'),
      },
      {
        _id: 'aud-2',
        user: 'usr-std-1',
        userEmail: 'student.rahul@gmail.com',
        role: 'student',
        action: 'APPLICATION_SUBMITTED',
        module: 'APPLICATION',
        details: { applicationNumber: 'IEM-2026-881023' },
        createdAt: new Date('2026-02-10T10:00:00Z'),
      },
      {
        _id: 'aud-3',
        user: 'usr-admin-1',
        userEmail: 'admin@iem.edu.in',
        role: 'admin',
        action: 'COURSE_CREATED',
        module: 'COURSE',
        details: { courseCode: 'BTECH-CSE', seats: 240 },
        createdAt: new Date('2026-01-05T09:00:00Z'),
      },
    ];

    this.initialized = true;
  }
}

const memoryDB = new InMemoryDB();
module.exports = memoryDB;
